import React,{useMemo,useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Upload,Factory,FileCode2,ChevronDown,Crosshair,Layers3,MousePointer2} from 'lucide-react';
import './style.css';
const API='http://localhost:8000';

function BoardViewer({scene,findings,onSelect}){
 const [hover,setHover]=useState(null);
 const [layer,setLayer]=useState('F.Cu');
 if(!scene?.bounds) return null;
 const b=scene.bounds, pad=3, W=820, H=500;
 const sx=(W-2*pad)/b.width_mm, sy=(H-2*pad)/b.height_mm, scale=Math.min(sx,sy);
 const ox=(W-b.width_mm*scale)/2, oy=(H-b.height_mm*scale)/2;
 const X=x=>ox+(x-b.min_x)*scale, Y=y=>H-(oy+(y-b.min_y)*scale);
 const criticalIds=new Set(findings.flatMap(f=>f.evidence?.geometry_ids||[]));
 const selected=new Map(findings.map(f=>[(f.evidence?.geometry_ids||[]).join(','),f]));
 const geomColor=id=>criticalIds.has(id)?'#ff4d4d':'#38d9a9';
 return <div className="boardCard">
   <div className="boardHead"><div><b>Spatial board view</b><span>KiCad geometry · mm</span></div><div className="boardTools"><Layers3 size={15}/><button className={layer==='F.Cu'?'active':''} onClick={()=>setLayer('F.Cu')}>F.Cu</button><button className={layer==='B.Cu'?'active':''} onClick={()=>setLayer('B.Cu')}>B.Cu</button></div></div>
   <div className="boardWrap">
    <svg viewBox={`0 0 ${W} ${H}`} className="boardSvg">
      <rect x={ox} y={H-oy-b.height_mm*scale} width={b.width_mm*scale} height={b.height_mm*scale} rx="2" className="boardBg"/>
      {scene.segments.filter(s=>s.layer===layer).map(s=><line key={s.id} x1={X(s.x1)} y1={Y(s.y1)} x2={X(s.x2)} y2={Y(s.y2)} stroke={geomColor(s.id)} strokeWidth={Math.max(1.5,s.width_mm*scale)} strokeLinecap="round" onMouseEnter={()=>setHover(s.id)} onMouseLeave={()=>setHover(null)} onClick={()=>onSelect(selected.get([s.id].join(',')))} className="geom"/>) }
      {scene.vias.map(v=><g key={v.id}><circle cx={X(v.x)} cy={Y(v.y)} r={Math.max(3,v.size_mm*scale/2)} className={criticalIds.has(v.id)?'via bad':'via'}/><circle cx={X(v.x)} cy={Y(v.y)} r={Math.max(1,v.drill_mm*scale/2)} className="drill"/></g>)}
      {scene.pads.map(p=><g key={p.id} onMouseEnter={()=>setHover(p.id)} onMouseLeave={()=>setHover(null)} onClick={()=>onSelect(selected.get([p.id].join(',')))} className="geom"><circle cx={X(p.x)} cy={Y(p.y)} r={Math.max(2,p.size_x_mm*scale/2)} className={criticalIds.has(p.id)?'pad bad':'pad'}/><circle cx={X(p.x)} cy={Y(p.y)} r={p.drill_mm?Math.max(1,p.drill_mm*scale/2):0} className="drill"/></g>)}
      {findings.map(f=>{const c=f.evidence?.coordinates?.[0]; if(!c)return null; return <circle key={f.id} cx={X((c[0]+c[2])/2)} cy={Y((c[1]+c[3])/2)} r="7" className="violationPulse"/>})}
    </svg>
    {hover&&<div className="hoverTag"><MousePointer2 size={13}/> {hover}</div>}
   </div>
   <div className="boardLegend"><span><i className="legendCopper"/> copper</span><span><i className="legendBad"/> violation</span><span><i className="legendVia"/> via/pad drill</span><span>{scene.nets.length} nets · {scene.segments.length} tracks · {scene.pads.length} pads</span></div>
 </div>
}

function App(){
 const [files,setFiles]=useState([]),[report,setReport]=useState(null),[loading,setLoading]=useState(false),[open,setOpen]=useState(null),[error,setError]=useState(''),[selected,setSelected]=useState(null),[knowledge,setKnowledge]=useState(null);
 useEffect(()=>{fetch(API+'/manufacturers').then(r=>r.json()).then(setKnowledge).catch(()=>{})},[]);
 const run=async()=>{setLoading(true);setError('');try{const fd=new FormData();files.forEach(f=>fd.append('files',f));const r=await fetch(API+'/analyze',{method:'POST',body:fd});const data=await r.json();if(!r.ok)throw new Error(data.detail||'Analysis failed');setReport(data)}catch(e){setError(e.message)}finally{setLoading(false)}};
 const selectFinding=f=>{setSelected(f?.id||null); if(f){const i=report.findings.findIndex(x=>x.id===f.id);setOpen(i)}};
 return <div className="page"><header><div className="brand"><Factory/> FORGEAGENT</div><div className="status"><span/> evidence-backed PCB review</div></header>
 <main><section className="hero"><div className="eyebrow">PCB MANUFACTURING INTELLIGENCE</div><h1>From KiCad geometry to manufacturability.</h1><p>Net-aware spatial analysis of tracks, pads and vias, backed by deterministic evidence and manufacturer capability matching.</p></section>
 <section className="card upload"><label><Upload size={30}/><b>Drop your manufacturing package</b><small>KiCad .kicad_pcb / Gerber / Excellon / BOM CSV</small><input type="file" multiple onChange={e=>setFiles([...e.target.files])}/></label><div className="files">{files.map(f=><span key={f.name}><FileCode2 size={14}/>{f.name}</span>)}</div><div className="actions"><button disabled={!files.length||loading} onClick={run}>{loading?'Running spatial inspection…':'Analyze manufacturing package'}</button><span>Geometry measurements happen deterministically; the agent receives evidence, not raw guesses.</span></div>{error&&<div className="error">{error}</div>}</section>
 {report&&<section className="results"><div className="summary"><Metric label="RISK SCORE" value={`${report.metrics.risk_score}/100`}/><Metric label="CONFIRMED" value={report.metrics.confirmed_violations||0}/><Metric label="WARNINGS" value={report.metrics.warnings||0}/><Metric label="GEOMETRY" value={`${report.metrics.tracks||0} tracks · ${report.metrics.pads||0} pads`}/><Metric label="NETS" value={report.metrics.nets||0}/><Metric label="BOARD" value={report.metrics.board?`${report.metrics.board.width_mm.toFixed(1)} × ${report.metrics.board.height_mm.toFixed(1)} mm`:`—`}/></div>
 <BoardViewer scene={report.metrics.board_scene} findings={report.findings} onSelect={selectFinding}/>
 <h2>Manufacturing findings</h2>{report.findings.map((f,i)=><article className={'finding '+(selected===f.id?'selected':'')} key={f.id} onClick={()=>{setOpen(open===i?null:i);setSelected(f.id)}}><div className={'severity '+f.severity}>!</div><div className="fbody"><div className="ftop"><b>{f.title}</b><ChevronDown className={open===i?'rot':''} size={17}/></div><p>{f.description}</p><small>{f.rule_id} · source: {f.source_tool} · {f.affected_artifact||'project'}</small>{open===i&&<div className="evidence"><b>Evidence</b><pre>{JSON.stringify(f.evidence,null,2)}</pre><div><b>Remediation</b><br/>{f.remediation}</div></div>}</div></article>)}
 <h2>Validation</h2><div className="validationCard"><b>ForgeAgent deterministic DFM</b><span>{report.findings.filter(f=>f.category==='fabrication'&&f.status==='VIOLATION').length} geometry violations</span><b>KiCad DRC independent check</b><span>{report.validation?.kicad_summary?`${report.validation.kicad_summary.violation_count} DRC violations · ${report.validation.kicad_summary.unconnected_item_count} unconnected items · ${report.validation.kicad_summary.total_diagnostics} total diagnostic records · source: ${report.validation.source}`:'Unavailable'}</span><b>Cross-validation</b><span>{report.validation?.cross_validation?.summary?`${report.validation.cross_validation.summary.corroborated} corroborated · ${report.validation.cross_validation.summary.forgeagent_only} ForgeAgent-only · ${report.validation.cross_validation.summary.kicad_only} KiCad-only DRC violations · ${report.validation.cross_validation.summary.unconnected_items||0} KiCad unconnected items · ${report.validation.cross_validation.summary.unmapped} unmapped`:report.validation?.reason}</span>{report.validation?.kicad_summary?.count_note&&<small>{report.validation.kicad_summary.count_note}</small>}{report.validation?.artifact&&<details><summary>KiCad DRC report artifact</summary><pre>{report.validation.artifact.content}</pre></details>}</div>
 <h2>Normalized manufacturing requirements</h2><div className="validationCard">{Object.entries(report.manufacturing_requirements||{}).map(([k,v])=><React.Fragment key={k}><b>{k.replaceAll('_',' ')}</b><span>{v==null?'UNKNOWN':String(v)} · {report.requirement_quality?.[k]?.status||'UNKNOWN'}{report.requirement_quality?.[k]?.reason?` — ${report.requirement_quality[k].reason}`:''}</span></React.Fragment>)}</div>
 <h2>Manufacturing routes</h2><div className="manufacturers">{(report.manufacturing_routes||[]).map((r,i)=><div className={'manufacturer '+(r.status==='PASS'?'ok':r.status==='FAIL'?'blocked':'conditional')} key={r.manufacturer_id+r.process_id}><div><Factory size={17}/><b>{r.manufacturer} — {r.process}</b></div><strong>PROCESS FEASIBILITY: {r.status}</strong><strong>OVERALL ROUTE: {r.overall_route_status}</strong><small>Fabrication: {r.fabrication_status} · Assembly: {r.assembly_status} · Procurement: {r.procurement_status}</small><small>Documented capability coverage: {r.capability_coverage}% ({r.documented_checks}/{r.applicable_checks} applicable requirements)</small><small>Checks: PASS {r.status_counts.PASS} · FAIL {r.status_counts.FAIL} · CONDITIONAL {r.status_counts.CONDITIONAL} · UNKNOWN {r.status_counts.UNKNOWN} · NOT_APPLICABLE {r.status_counts.NOT_APPLICABLE}</small><details><summary>Capability evidence ({r.matrix.length} entries)</summary><div className="evidenceTable">{r.matrix.map((m,j)=><div className="planRow" key={j}><b>{m.parameter}: {m.requirement==null?'unmeasured':`${m.requirement} ${m.requirement_unit||m.unit||''}`}</b><span>{m.status} · published {m.capability==null?'not documented':`${m.capability} ${m.unit}`} · conditions {JSON.stringify(m.conditions||{})}<br/>{m.reason}{m.source&&<><br/><a href={m.source.url} target="_blank" rel="noreferrer">{m.source.title}</a> · {m.source.evidence_note}</>}</span></div>)}</div></details><small>Capabilities may vary by process, stackup, material, copper weight, board geometry, and order configuration. Final manufacturability is subject to manufacturer review.</small></div>)}</div>
 <h2>Manufacturer knowledge base</h2><div className="manufacturers">{(knowledge?.manufacturers||[]).map(m=><div className="manufacturer" key={m.manufacturer_id}><b>{m.name}</b>{m.processes.map(p=><details key={p.process_id}><summary>{p.name} · {p.capabilities.length} sourced · {p.unknown_capabilities?.length||0} undocumented parameters</summary>{p.capabilities.map((c,j)=><small key={j}>{c.parameter}: {c.value} {c.unit} · {c.capability_type} · conditions {JSON.stringify(c.conditions)}<br/><a href={c.source.url} target="_blank" rel="noreferrer">{c.source.title}</a> · verified {c.last_verified_at} · {c.source.evidence_note}</small>)}{p.unknown_capabilities?.map((c,j)=><small key={'u'+j}>{c.parameter}: UNKNOWN · not verified in the public process profile</small>)}</details>)}</div>)}</div>
 <h2>Resolution plan</h2><div className="resolution"><div className="planStatus">{report.manufacturing_plan.status.replace('_',' ').toUpperCase()}</div>{report.manufacturing_plan.actions.map(a=><div className="planRow" key={a.finding_id}><b>{a.title}</b><span>{a.details}</span></div>)}{report.manufacturing_plan.options.map((o,i)=><div className="planOption" key={i}><b>{o.title}</b><span>{o.reason||o.details||''}</span></div>)}</div>
 <h2>Quote scenarios</h2><div className="manufacturers">{report.quote_scenarios.map(q=><div className="manufacturer" key={q.manufacturer}><div><Factory size={17}/><b>{q.manufacturer}</b></div><strong>{q.status.toUpperCase()}</strong><div className="quote">{q.estimate_type} No live pricing or lead time is available.</div></div>)}</div>
 <h2>Agent trace</h2><div className="trace">{report.trace.map(x=><div className="traceRow" key={x.step}><div className="dot">{x.step}</div><div><b>{x.agent}</b><span>{x.action}</span></div><em>completed</em></div>)}</div></section>}<section className="card"><h2>Manufacturer knowledge base</h2><p>Official process capability records and documented information gaps, available independently of a board analysis.</p><div className="manufacturers">{(knowledge?.manufacturers||[]).map(m=><div className="manufacturer" key={m.manufacturer_id}><b>{m.name}</b>{m.processes.map(p=><details key={p.process_id}><summary>{p.name} · {p.capabilities.length} sourced · {p.unknown_capabilities?.length||0} undocumented parameters</summary>{p.capabilities.map((c,j)=><small key={j}>{c.parameter}: {c.value} {c.unit} · {c.capability_type} · conditions {JSON.stringify(c.conditions)}<br/><a href={c.source.url} target="_blank" rel="noreferrer">{c.source.title}</a> · verified {c.last_verified_at} · {c.source.evidence_note}</small>)}{p.unknown_capabilities?.map((c,j)=><small key={'u'+j}>{c.parameter}: UNKNOWN · not verified in the public process profile</small>)}</details>)}</div>)}</div></section></main></div>
}
function Metric({label,value}){return <div className="metric"><small>{label}</small><strong>{value}</strong></div>}
createRoot(document.getElementById('root')).render(<App/>);
